### ISSUE TITLE
Error of playing HKMP

### ISSUE THREAD

**Issue by Elimen210** [TheMulhima/Lumafly#101]
### Lumafly Version

v3.2.0.0

### Hollow Knight Version

v1.4.3.2

### Steps to Reproduce

J'ai installé Steam et Hollow Knight je l'ai eu en crack, ensuite j'ai installé le mod HKMP et HKMP Pouch sur Lumafly.

### Expected Behaviour

Lancer Hollow Knight avec le mod sans problème

### Actual Behaviour

A chaque fois que je lance le jeu ça lance Steam et puisque j'ai pas eu le jeu sur steam et par steam et ben on me met clé de license pas acheté (ou un truc du genre) et ça m'empèche de lancer le mod et de jouer avec mes amis :(

### Errors and Logs

Unable to launch the game

Lumafly Version: 3.2.0.0

System.ComponentModel.Win32Exception (0x800401F5): An error occurred trying to start process 'steam://rungameid/367520' with working directory 'C:\Users\elime\Downloads'. Application introuvable.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Lumafly.ViewModels.InfoViewModel._LaunchGame(Nullable`1 isVanilla) in D:\a\Lumafly\Lumafly\Lumafly\ViewModels\InfoViewModel.cs:line 88

**Comment by TheMulhima** [comment]
The installer is not designed for cracked versions and may not work as expected for them. Please buy the game instead
