### ISSUE TITLE
Lumafly freezing without explaination

### ISSUE THREAD

**Issue by duvuwu** [TheMulhima/Lumafly#102]
### Lumafly Version

v3.2.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Run the Linux Lumafly executable on my system (alpine linux, flatpak steam)

### Expected Behaviour

The program just to run.

### Actual Behaviour

The program freezes at some point, the loading animation stops playing and it can't even resize. This seems to happen somewhere in the block at line 93 installer.cs given the logs, but that's just a hunch, I don't do c#. There aren't any error or exception logs. It seems to be creating and destroying LWPs forever after it freezes (ran it through gdb)

### Errors and Logs

[ModInstaller.log](https://github.com/TheMulhima/Lumafly/files/14618856/ModInstaller.log)

**Comment by duvuwu** [comment]
If you need any more details just lmk

**Comment by TheMulhima** [comment]
Unfortunately I don't have enough information to debug and fix this issue.
