### ISSUE TITLE
CUstom knight not working,cant toggle off custom knight or enemy hp bar,only have hp bar custom knight and damage values

### ISSUE THREAD

**Issue by SilSonWen** [TheMulhima/Lumafly#119]
### Lumafly Version

v3.2.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

have damage values,enemy hpbar,custom knight

### Expected Behaviour

Normal HK modded,mods would SHOW UP, custom knight would show up.

### Actual Behaviour

mods not apperaing on list,custom knight show normal knight

### Errors and Logs

<img width="393" alt="Screenshot 2024-09-01 193621" src="https://github.com/user-attachments/assets/65f62086-2135-4c19-9340-2b587d857ab7">

**Comment by DwarfWoot** [comment]
For help with modding itself, you'll want to join the Modding Discord (linked in the main page of the installer), and open a a Support post including your Modlog file
