### ISSUE TITLE
Remembering version when moving mods manually

### ISSUE THREAD

**Issue by Acu1000** [TheMulhima/Lumafly#69]
### Explanation of the new feature

Currently when you remove a mod manually, put it somewhere else (for example for backup or testing purposes) and use scarab, when you later put the mod back into the game's mod folder, Scarab thinks the mod version is not from modlinks and shows the update button near it, despite the mod being up to date. I believe this is caused by the fact that versions of the mods are stored in the InstalledMods.json file, which is in a completely different location.

My idea on how to fix this is to have Scarab add a "version" file to the mod's directory that contains just the current version of the mod, whenever a mod from modlinks is installed/updated. This way the version wouldn't get forgotten whenever user moves the mod files somewhere else and Scarab could recognize up-to-date modlinks mods without depending on the .json file.

The version in the .json would still take priority, but if the mod is not present in the .json file, it should automatically put the version there from the created file.
![temp](https://github.com/TheMulhima/Scarab/assets/140196544/650be0a3-ca43-4d51-af24-3eac7a780687)

**Comment by TheMulhima** [comment]
Shouldn't be a problem anymore with modpacks.
