### ISSUE TITLE
o mod nao instala

### ISSUE THREAD

**Issue by Blitzooo** [TheMulhima/Lumafly#71]
### Scarab Version

v2.3.0.0

### Hollow Knight Version

1.5.78.11833

### Steps to Reproduce

eu nao sei oque tem de errado

### Expected Behaviour

eu queria colocar skins no knight

### Actual Behaviour

nao instala nenhum mod 

### Errors and Logs

![image](https://github.com/TheMulhima/Scarab/assets/91688213/afb20cae-e34f-4ce5-b03e-d30cdbedd6fd)

**Comment by TheMulhima** [comment]
você pode pressionar o botão "copiar erro" e colar o erro aqui
