### ISSUE TITLE
problem starting hollow knight

### ISSUE THREAD

**Issue by Ragnaroki123** [TheMulhima/Lumafly#76]
### Lumafly Version

v1.3.0.0

### Hollow Knight Version

v1.5.68.11808

### Steps to Reproduce

My Hollow Knight is not original, so when I try to open the game (the path is already correct) it takes me to Steam

### Expected Behaviour

I expected it to open the pirated game correctly

### Actual Behaviour

He opened Steam, but I don't have money to buy the original

### Errors and Logs

Invalid Hollow Knight exe! Please select the Hollow Knight exe or its shortcut

**Comment by TheMulhima** [comment]
We don't support pirated versions. Sorry.
