### ISSUE TITLE
Filter Mods tab text not fully displayed in Chinese

### ISSUE THREAD

**Issue by lxymahatma** [TheMulhima/Lumafly#77]
### Lumafly Version

v3.1.0.0

### Hollow Knight Version

\

### Steps to Reproduce

\

### Expected Behaviour

same with other languages, full text display
currently the bottom part is a bit missing

### Actual Behaviour

![image](https://github.com/TheMulhima/Lumafly/assets/66151783/7ef58b35-2e46-48fd-8099-234bce6a6869)

### Errors and Logs

\

**Comment by TheMulhima** [comment]
These are one of the new texts added in v3 update that hasn't been localized yet. I unfortunately don't know chinese. If you are willing to help with adding this translation, you can read about it here <https://github.com/TheMulhima/Lumafly/tree/localizations#readme>

**Comment by lxymahatma** [comment]
> These are one of the new texts added in v3 update that hasn't been localized yet. I unfortunately don't know chinese. If you are willing to help with adding this translation, you can read about it here https://github.com/TheMulhima/Lumafly/tree/localizations#readme

Actually i mean the category text, 全部，已安装，已启用 etc
the character bottom part is covered by the separate line

for the translation stuff, i use resx and crowdin as the system, i think crowdin also supports csv format so might be easier to use crowdin?
it has github integrations with automatic update pushes and make pr🤔

**Comment by TheMulhima** [comment]
It uses static resx files. No automatic updates and such. Rider allows importing/exporting from CSV to resx files so that's why it's csv.

Also everyone who have helped in the translation are on is discord  so if they don't wanna pr then they can just send it on the channel. Also they are programmers so pring isn't an issue

**Comment by lxymahatma** [comment]
> It uses static resx files. No automatic updates and such. Rider allows importing/exporting from CSV to resx files so that's why it's csv.
> 
> Also everyone who have helped in the translation are on is discord so if they don't wanna pr then they can just send it on the channel. Also they are programmers so pring isn't an issue

oh that make sense lol

but crowdin do have the function to push and make pr if u set up github integration correctly 👀
![image](https://github.com/TheMulhima/Lumafly/assets/66151783/dabfcbd1-2e53-4422-b8e8-abe789ebf418)
and it will update the key if u push to the correct branch
like in my project whenever i have new string updated in dev/rewrite branch after sync i can see it on crowdin

but well, i mean, if csv work and u dont have any issues with that then it's also good keeping it lol

**Comment by TheMulhima** [comment]
<img width="606" alt="image" src="https://github.com/TheMulhima/Lumafly/assets/81007262/ee3f474b-bee4-4187-a313-d3fe19dfe7b9">
it seems to be fine on my end

**Comment by lxymahatma** [comment]
> <img alt="image" width="606" src="https://user-images.githubusercontent.com/81007262/270143409-ee3f474b-bee4-4187-a313-d3fe19dfe7b9.png"> it seems to be fine on my end

![image](https://github.com/TheMulhima/Lumafly/assets/66151783/9ee6d2c0-8b37-4c6d-80c5-4f5d1914ad48)
hmm interesting

**Comment by lxymahatma** [comment]
seems like caused by padding 
![image](https://github.com/TheMulhima/Lumafly/assets/66151783/a0fe5b8c-8044-4497-9e68-9d60df2bd612)
![image](https://github.com/TheMulhima/Lumafly/assets/66151783/8c3bd657-4a15-4c65-ac4b-d29771ed569e)
if i change tb to 0 it shows the full text
