### ISSUE TITLE
app window pop up and disappers

### ISSUE THREAD

**Issue by El-Dong** [TheMulhima/Lumafly#92]
### Lumafly Version

v3.2.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

when clicking .exe, the window pops up and disappears
i've fixed the problem by deleting former installed (months ago) HKModinstaller folder.

### Expected Behaviour

\

### Actual Behaviour

\

### Errors and Logs

\

**Comment by TheMulhima** [comment]
Unfortunately I don't have enough information to debug and fix the issue
