### ISSUE TITLE
it doesnt work!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by vegetop** [TheMulhima/Lumafly#98]
### Lumafly Version

it doesent wor kwhen i choose hollow knight also its the latest

### Hollow Knight Version

its the latest

### Steps to Reproduce

download hollow knight on xbox app

### Expected Behaviour

terrable

### Actual Behaviour

terrable

### Errors and Logs

invalid hollow knight exe please select the hollow knight exe or its shortcut

**Comment by Ruttie2006** [comment]
Too little information is provided.
Do the following:
- Get a screenshot of the error you are experiencing
- Make a post in the Hollow Knight Modding discord (https://discord.com/hk-modding)  

This is not the place to post about your problems modding the game, this is for bug reports.
I would also recommend using a translator such as https://deepl.com if you are having trouble using english.
